version: '3.8'

services:
  backend:
    ports:
      - "81:81"
    networks:
      - internal
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --host dev.himaaa.xyz --port 81

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - internal
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config:  

networks:
  internal: