version: '3.8'

services:
  backend:
    ports:
      - "80:80"
    build:
      context: .backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --host dev.himaaa.xyz --port 80
