version: '3.8'

services:
  backend:
    expose:
      - 8000
    build: 
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  caddy-data:
  caddy-config: